#!/bin/bash
# Read with Chandra everything that is waiting to be read, in order, through the scheduler.
#
#   tools/references/ocr_read_chain.sh            # the whole chain, blocking
#
# There is one list of files waiting: tools/references/pending_ocr.txt. A file goes on it when its PDF arrives and
# comes off when it has been read. It replaced three lists named after the passes that built the archive
# (ocr_layer_files, scanned_native_layer_files, chandra_pass3_files); by the time they were deleted, 230 of their
# 233 entries were long since read and the remaining three were two pointer stubs that must never be read and one
# paper that had just arrived. A list named after a pass tells you what happened once; a list of what is pending
# tells you what to do now, and empty is the resting state.
#
# The page-level repairs are separate because they are not whole files. Each names the pages of one file to read
# again, and each is generated by the instrument that found the damage:
#   - references/work/mangled_repair_list.txt, from find_mangled_pages.py: pages whose publisher font encoding
#     makes the text layer wrong, so equations and constants extract corrupt.
#   - references/work/repair_list.txt, from audit_orientation.py: pages read sideways before the recipe turned
#     pages upright.
#
# Every stage is resumable from references/text/manifest.jsonl, so an interrupted chain is restarted by running it
# again. A file whose text is a one-page pointer stub is skipped by chandra_pages.py itself, not by being kept off
# a list.
#
# The reader is an HTTP client of a Chandra server that must already answer on 127.0.0.1:8000; the chain waits for
# it rather than starting one, because the server may be run outside the scheduler. Orientation is tesseract on the
# job's own cores (see chandra_pages.py), which is why the passes ask for many: with too few, the card idles while
# a file's pages are being turned.
set -u
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"; cd "$ROOT"
PY=${CHANDRA_PYTHON:-$HOME/.venvs/chandra-vllm/bin/python}
WORK="$ROOT/references/work"; mkdir -p "$WORK"
# Rendered pages go to disk, not to RAM. /tmp here is a tmpfs, and since the reader renders every page of a file before sending it,
# the default temporary directory turns a large book into gigabytes of resident memory and the machine
# swaps: throughput fell to a third of its rate with the card still reading 100 percent busy.
export TMPDIR="$WORK/tmp"; mkdir -p "$TMPDIR"
export OMP_THREAD_LIMIT=1   # one thread per tesseract; the pool size is the parallelism
CORES=${OCR_CORES:-12}; MEM=${OCR_MEM:-20G}
say() { echo "=== $(date +%H:%M:%S) $*"; }

say "waiting for the Chandra server on 127.0.0.1:8000"
until curl -s --max-time 5 127.0.0.1:8000/metrics >/dev/null; do sleep 60; done

PENDING="$ROOT/tools/references/pending_ocr.txt"
if [ -s "$PENDING" ]; then
  say "pending: $(grep -c . "$PENDING") file(s) waiting to be read"
  qrun -p light -m "$MEM" -c "$CORES" -t 12:00:00 -- "$PY" tools/references/chandra_pages.py \
    "$PENDING" --method vllm --batch 16 --resume 2>&1 |
    grep -iE 'pages \(|stub|Traceback|Error|done|OOM'
else
  say "nothing pending"
fi

say "finding pages whose font encoding makes the text layer wrong"
"$PY" tools/references/find_mangled_pages.py
if [ -s "$WORK/mangled_repair_list.txt" ]; then
  say "repair pass: the pages that extract corrupt"
  qrun -p light -m "$MEM" -c "$CORES" -t 8:00:00 -- "$PY" tools/references/chandra_pages.py \
    "$WORK/mangled_repair_list.txt" --repair --method vllm --batch 16 2>&1 |
    grep -iE 'repaired|Traceback|Error|done'
fi

say "waiting for the rotation audit's repair list"
until [ -f "$WORK/audit_done" ]; do sleep 60; done
if [ -s "$WORK/repair_list.txt" ]; then
  say "repair pass: the pages read sideways"
  qrun -p light -m "$MEM" -c "$CORES" -t 8:00:00 -- "$PY" tools/references/chandra_pages.py \
    "$WORK/repair_list.txt" --repair --method vllm --batch 16 2>&1 | grep -iE 'repaired|Traceback|Error|done'
else
  say "no sideways pages to repair"
fi
# Tables read by OCR are not kept: prose comes back faithful, tables do not, and a number that cannot be verified
# must not be quotable with a page citation. Each becomes a marker with its caption and page (strip_ocr_tables.py).
say "removing OCR'd table cells from the text"
"$PY" tools/references/strip_ocr_tables.py --apply
say "reading chain complete"
